# Generated by Django 2.1.2 on 2019-03-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VendorRegister',
            fields=[
                ('vendor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('company_address', models.CharField(max_length=50)),
                ('contact_no', models.IntegerField()),
                ('email_id', models.EmailField(max_length=100)),
                ('username', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
                ('status', models.CharField(max_length=30)),
            ],
        ),
    ]
