# Generated by Django 2.1.2 on 2019-03-20 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gd_vendor', '0002_dispatcher_payments_space'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
