# Generated by Django 2.1.2 on 2019-03-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accountant_Register',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=30)),
                ('address', models.TextField(max_length=400)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.IntegerField()),
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=30)),
                ('address', models.TextField(max_length=400)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.IntegerField()),
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory_Register',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=30)),
                ('address', models.TextField(max_length=400)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.IntegerField()),
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Manager_Register',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=30)),
                ('address', models.TextField(max_length=400)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.IntegerField()),
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor_Register',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=30)),
                ('address', models.TextField(max_length=400)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.IntegerField()),
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
