# Generated by Django 2.1.2 on 2019-03-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gd_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoDown',
            fields=[
                ('godown_id', models.IntegerField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=30)),
                ('capacity', models.IntegerField()),
                ('godown_manager', models.CharField(max_length=50)),
                ('inventory_manager', models.CharField(max_length=50)),
            ],
        ),
    ]
