# Generated by Django 2.1.2 on 2019-03-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gd_admin', '0002_godown'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=30)),
                ('address', models.TextField(max_length=400)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.IntegerField()),
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
