# Generated by Django 2.1.2 on 2019-03-24 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gd_admin', '0003_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accountant_Register',
        ),
        migrations.DeleteModel(
            name='Inventory_Register',
        ),
        migrations.DeleteModel(
            name='Manager_Register',
        ),
    ]
