# Generated by Django 2.1.2 on 2019-03-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inbox_Mails',
            fields=[
                ('mail_id', models.AutoField(primary_key=True, serialize=False)),
                ('frm', models.CharField(max_length=30)),
                ('to', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=50)),
                ('body', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
                ('usertype', models.CharField(max_length=30)),
            ],
        ),
    ]
